#pragma once

#include "elfparser/model/enums/ElfClass.h"
#include "elfparser/model/enums/ElfData.h"
#include "elfparser/model/enums/ElfOsAbi.h"
#include "elfparser/model/enums/ElfType.h"
#include "elfparser/model/enums/ElfMachine.h"
#include "elfparser/model/enums/ElfSegmentType.h"
#include "elfparser/model/enums/ElfSectionType.h"
#include "elfparser/model/enums/ElfDynamicTag.h"
#include "elfparser/model/enums/ElfNoteType.h"
#include "elfparser/model/enums/ElfSymbolBinding.h"
#include "elfparser/model/enums/ElfSymbolType.h"
#include "elfparser/model/enums/ElfSymbolVisibility.h"
#include "elfparser/model/enums/ElfVersionType.h"

#include "elfparser/model/structs/ElfEhdr.h"
#include "elfparser/model/structs/ElfPhdr.h"
#include "elfparser/model/structs/ElfShdr.h"
#include "elfparser/model/structs/ElfSym.h"
#include "elfparser/model/structs/ElfDyn.h"
#include "elfparser/model/structs/ElfRel.h"
#include "elfparser/model/structs/ElfNhdr.h"
#include "elfparser/model/structs/ElfHash.h"
#include "elfparser/model/structs/ElfVerDef.h"
#include "elfparser/model/structs/ElfVerNeed.h"
#include "elfparser/model/structs/ElfVerSym.h"
